import type { Metadata } from 'next'
import './globals.css'
import { ModuleRegistry, AllCommunityModule } from 'ag-grid-community'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    ModuleRegistry.registerModules([AllCommunityModule])
    return (
        <html lang="en">
            <head>
                <title>Nyanberg - Paradox Games Save Viewer</title>
            </head>
            <body>{children}</body>
        </html>
    )
}
